defmodule Mix.Tasks.Condukt.Workspace.Prepare do
  @shortdoc "Derive a cooperative workspace image for Sandbox.Net"

  @moduledoc """
  Builds a derived image from `<input-image>` that trusts the per-session
  CA mounted by `Condukt.Sandbox.Net` at runtime, so the egress sidecar
  can terminate TLS and capture method/path/headers/body for the HTTPS
  traffic the agent makes on `Condukt.Sandbox.Kubernetes` pods.

  `Condukt.Sandbox.Net` requires a cooperative image: without one the
  TLS handshake between the workspace and the sidecar fails and the
  request emits a `tls_handshake_failed` event rather than flowing.
  Run this task once per base image you want to ship under sandbox-net.

  ## Usage

      mix condukt.workspace.prepare <input-image> --output <output-image>

      mix condukt.workspace.prepare node:20-bookworm \\
        --output ghcr.io/acme/agent:1.4-condukt \\
        --push

  ## What it adds to the image

    * `ca-certificates` and a runtime entrypoint shim that installs the
      mounted CA at `/etc/condukt/ca.pem` into the system trust store
      (Debian/Ubuntu/Alpine flavors auto-detected).
    * Env vars for runtimes that ignore the system trust store:
      `NODE_EXTRA_CA_CERTS`, `REQUESTS_CA_BUNDLE`, `SSL_CERT_FILE`,
      `PIP_CERT`, `CURL_CA_BUNDLE`, `GIT_SSL_CAINFO`.
    * An entrypoint that runs the shim before `exec`ing into the
      original command. The original CMD is preserved automatically.

  ## Options

    * `--output OUTPUT_REF` — required. Tag of the resulting image.
    * `--push` — push the resulting image to the registry encoded in
      `--output` after building. Off by default.
    * `--builder NAME` — `docker buildx` builder name. Defaults to the
      currently selected builder.
    * `--dockerfile-output PATH` — write the generated Dockerfile to
      this path for inspection instead of building. When set, no
      `docker buildx` invocation runs.
    * `--platform LIST` — comma-separated buildx platforms (e.g.
      `linux/amd64,linux/arm64`). Defaults to `linux/amd64,linux/arm64`
      when `--push`, otherwise unset (single-arch native).
    * `--preserve-entrypoint COMMAND` — if the source image has a
      non-trivial `ENTRYPOINT`, pass it here as a shell-quoted command
      so the shim can `exec` into it after the CA install step.
  """

  use Mix.Task

  @switches [
    output: :string,
    push: :boolean,
    builder: :string,
    dockerfile_output: :string,
    platform: :string,
    preserve_entrypoint: :string
  ]

  @ca_mount_path "/etc/condukt"
  @ca_filename "ca.pem"

  @impl Mix.Task
  def run(args) do
    {opts, positional, invalid} = OptionParser.parse(args, strict: @switches)

    if invalid != [] do
      Mix.raise("unknown options: #{inspect(invalid)}")
    end

    input =
      case positional do
        [input] -> input
        _ -> Mix.raise("expected: mix condukt.workspace.prepare <input-image> --output <output-image>")
      end

    output = Keyword.fetch!(opts, :output)

    dockerfile = render_dockerfile(input, opts)
    entrypoint = render_entrypoint(opts)

    case Keyword.get(opts, :dockerfile_output) do
      nil -> build_image(dockerfile, entrypoint, output, opts)
      path -> write_dockerfile_only(path, dockerfile, entrypoint)
    end
  end

  defp render_dockerfile(input, opts) do
    preserve = Keyword.get(opts, :preserve_entrypoint)
    preserve_clause = if preserve, do: ~s(ENV CONDUKT_NET_PRESERVED_ENTRYPOINT="#{preserve}"\n), else: ""

    """
    # syntax=docker/dockerfile:1
    # Generated by `mix condukt.workspace.prepare`. Do not hand-edit.

    FROM #{input}

    USER root

    COPY condukt-net-entrypoint.sh /usr/local/bin/condukt-net-entrypoint
    RUN chmod 0755 /usr/local/bin/condukt-net-entrypoint

    # Install ca-certificates for whichever flavor the base image is.
    # We try apt-get (Debian/Ubuntu) first, then apk (Alpine), then yum
    # (RHEL family). Failure to install is non-fatal: the entrypoint
    # shim handles missing ca-certificates by falling back to env-var
    # only CA wiring (NODE_EXTRA_CA_CERTS et al), which covers most
    # language runtimes even when the system trust store cannot be
    # updated.
    RUN set -eux; \\
        if command -v apt-get >/dev/null 2>&1; then \\
          apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*; \\
        elif command -v apk >/dev/null 2>&1; then \\
          apk add --no-cache ca-certificates; \\
        elif command -v yum >/dev/null 2>&1; then \\
          yum install -y ca-certificates && yum clean all; \\
        else \\
          echo "no supported package manager found; falling back to env-only CA trust"; \\
        fi

    ENV NODE_EXTRA_CA_CERTS=#{@ca_mount_path}/#{@ca_filename}
    ENV REQUESTS_CA_BUNDLE=#{@ca_mount_path}/#{@ca_filename}
    ENV SSL_CERT_FILE=#{@ca_mount_path}/#{@ca_filename}
    ENV PIP_CERT=#{@ca_mount_path}/#{@ca_filename}
    ENV CURL_CA_BUNDLE=#{@ca_mount_path}/#{@ca_filename}
    ENV GIT_SSL_CAINFO=#{@ca_mount_path}/#{@ca_filename}
    #{preserve_clause}
    ENTRYPOINT ["/usr/local/bin/condukt-net-entrypoint"]
    """
  end

  defp render_entrypoint(_opts) do
    """
    #!/bin/sh
    set -e

    CA_SRC="#{@ca_mount_path}/#{@ca_filename}"

    if [ -f "$CA_SRC" ]; then
      # Try to install into the system trust store. Errors here are
      # non-fatal: the env vars set in the Dockerfile point most
      # language runtimes at the mounted CA directly.
      if command -v update-ca-certificates >/dev/null 2>&1; then
        cp "$CA_SRC" /usr/local/share/ca-certificates/condukt-egress.crt 2>/dev/null || true
        update-ca-certificates >/dev/null 2>&1 || true
      elif command -v update-ca-trust >/dev/null 2>&1; then
        cp "$CA_SRC" /etc/pki/ca-trust/source/anchors/condukt-egress.crt 2>/dev/null || true
        update-ca-trust >/dev/null 2>&1 || true
      fi
    fi

    # If the source image had a non-trivial ENTRYPOINT, chain into it
    # so the user's contract is preserved.
    if [ -n "${CONDUKT_NET_PRESERVED_ENTRYPOINT:-}" ]; then
      # shellcheck disable=SC2086
      exec sh -c "$CONDUKT_NET_PRESERVED_ENTRYPOINT \\"$@\\"" -- "$@"
    fi

    exec "$@"
    """
  end

  defp build_image(dockerfile, entrypoint, output, opts) do
    push? = Keyword.get(opts, :push, false)
    builder = Keyword.get(opts, :builder)
    platform = Keyword.get(opts, :platform, default_platform(push?))

    Mix.shell().info("==> Preparing cooperative workspace image #{output}")

    context = make_context_dir(dockerfile, entrypoint)

    try do
      argv = build_argv(output, context, push?, builder, platform)
      Mix.shell().info("    $ docker " <> Enum.join(argv, " "))

      case run_docker(argv) do
        :ok -> Mix.shell().info("==> Built #{output}")
        {:error, code} -> Mix.raise("docker buildx exited #{code}")
      end
    after
      File.rm_rf!(context)
    end
  end

  defp write_dockerfile_only(path, dockerfile, entrypoint) do
    File.mkdir_p!(path)
    File.write!(Path.join(path, "Dockerfile"), dockerfile)
    File.write!(Path.join(path, "condukt-net-entrypoint.sh"), entrypoint)
    Mix.shell().info("==> Wrote Dockerfile + shim to #{path}")
  end

  defp make_context_dir(dockerfile, entrypoint) do
    base = System.tmp_dir!()
    dir = Path.join(base, "condukt-workspace-prepare-#{System.unique_integer([:positive])}")
    File.mkdir_p!(dir)
    File.write!(Path.join(dir, "Dockerfile"), dockerfile)
    File.write!(Path.join(dir, "condukt-net-entrypoint.sh"), entrypoint)
    dir
  end

  defp build_argv(output, context, push?, builder, platform) do
    base = ["buildx", "build", "-t", output]
    base = if builder, do: base ++ ["--builder", builder], else: base
    base = if platform, do: base ++ ["--platform", platform], else: base
    base = if push?, do: base ++ ["--push"], else: base ++ ["--load"]
    base ++ [context]
  end

  defp default_platform(true), do: "linux/amd64,linux/arm64"
  defp default_platform(false), do: nil

  defp run_docker(argv) do
    case MuonTrap.cmd("docker", argv, into: IO.stream(:stdio, :line)) do
      {_, 0} -> :ok
      {_, code} -> {:error, code}
    end
  end
end
